### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by codebryo** [gauravtiwari/rails-webpacker#1]
Hi,

thanks a lot for this repo. It helped me a lot in understanding how to use webpack with rails 5. 
And also tought me a lot of other steps.

I am now struggling with deploying my app to heroku. It dies on the `nodejs` buildpack.
Did you use a custom buildpack? Or how do you get it running there?

Best,
Roman

**Comment by gauravtiwari** [comment]
Hey Roman, Yeah, you have to add the node buildpack - `heroku buildpacks:add --index 1 heroku/nodejs`. I have added a blank `package.json` and `yarn.lock` in root folder to trick heroku to detect it as node app and also install yarn. I think it should work after that :)

**Comment by gauravtiwari** [comment]
Hey @codebryo Were you able to work this out?

**Comment by codebryo** [comment]
Hi. Yes i did thanks. I had to add the custom assets:precompile hook. Added it into the Rakefile. Now its wirking nicely. Thanks a lot.

**Comment by taboularasa** [comment]
@codebryo what is the custom assets:precompile hook?

**Comment by gauravtiwari** [comment]
Hey, Please take a look at this - https://github.com/gauravtiwari/rails-webpacker/blob/master/lib/tasks/assets.rake

**Comment by taboularasa** [comment]
thanks @gauravtiwari

**Comment by gauravtiwari** [comment]
@codebryo @taboularasa Looks like deployment should now work without `assets:precompile` hook as package.json is returned to it's place - https://github.com/rails/webpacker/pull/101

**Comment by taboularasa** [comment]
@gauravtiwari hey thanks for the update, appreciate that!

**Comment by codebryo** [comment]
@gauravtiwari oh, didn't even notice. Thanks for the headsup... this means I will have to move some stuff and scripts locally around again, as I made my `jest` testsuite to leverage that as well.... hmm
