### ISSUE TITLE
The react router page is broken

### ISSUE THREAD

**Issue by xdmx** [gauravtiwari/rails-webpacker#3]
It may be because the Link in v4.0 is in `react-router-dom` and not in `react-router`

The console also shows a missing value for the history props

**Comment by gauravtiwari** [comment]
@xdmx Thanks for pointing out. Try this one out please - https://github.com/gauravtiwari/webpacker-react-frontend

**Comment by gauravtiwari** [comment]
Please make a PR if you know the fix 👍  thanks
