### ISSUE TITLE
more example

### ISSUE THREAD

**Issue by multpix** [gauravtiwari/rails-webpacker#4]
With webpacker gem, how to send data to react component props from view variables eg. Pls simple exemple if you can.

**Comment by gauravtiwari** [comment]
@multpix Please use this  - https://github.com/renchap/webpacker-react

**Comment by multpix** [comment]
thanks, I'm looking at:
https://github.com/gauravtiwari/webpacker-react-frontend
https://github.com/renchap/webpacker-react
its great)
