### ISSUE TITLE
Pass variables as props from views to components

### ISSUE THREAD

**Issue by coisnepe** [gauravtiwari/rails-webpacker#5]
Hey @gauravtiwari, first of all, thanks for all your time and effort working on webpacker!

I've been trying to figure out how to pass props from standard erb views to my vue components, but without success so far...

Something along the lines of
```ruby
# app/views/users/show.html.erb
<user-card username="gauravtiwari"></user-card>
<%= javascript_pack_tag 'user-card' %>
```

```js
// app/javascript/packs/user-card.js
import "user-card";

// app/javascript/user-card/index.js
<template>
  <div>
    <p>{{ message }}</p>
    <p>{{ username }}</p>
  </div>
</template>

<script>
export default {
  data: () => {
    return {
      message: "Hello Vue <3",
      username: ""
    }
  }
}
</script>
```

But it's just not working... Your help would be hugely appreciated!

**Comment by sebbean** [comment]
think you need a `props` property?

https://vuejs.org/v2/guide/components.html#Passing-Data-with-Props

**Comment by gauravtiwari** [comment]
@coisnepe Just pushed an example based on @sebbean recommendation. Demo here: https://rails-webpacker.herokuapp.com/home-vue-version 😄

**Comment by coisnepe** [comment]
@gauravtiwari Sorry for the late reply! Thanks for taking the time to find and push a potential solution.

Another solution I just found is to use the `content_tag` helper, which makes it extremely easy to pass props to the element.

```ruby
<%= content_tag :div,
  id: "user-card",
  data: {
    message: t("hello"),
    name: @user.name
} do %>
<% end %>
```
```html
<div id="user-card" data-name="gauravtiwari" data-message="Bonjour!"></div>
```

Hope this helps! Maybe it could be included in the doc somewhere, either in _rails/webpacker_ or your project?

Credit goes to @excid3 and his [VueJS+Rails](https://gorails.com/episodes/using-vuejs-for-nested-forms-part-1?autoplay=1) video

**Comment by multpix** [comment]
@coisnepe thank,
interesting video!

**Comment by gauravtiwari** [comment]
Cool 👍

**Comment by fathur-bookdoc** [comment]
Just to update if anyone encounter this issue. The best way to solve this problem is mention in this video

https://gorails.com/episodes/vuejs-components-in-rails-views
